# Generated by Django 3.2.4 on 2021-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(blank=True, default='0123456789', max_length=10),
        ),
    ]
