# Generated by Django 3.2.4 on 2021-06-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
